
spring:
  datasource:
    username: root
    password: 1212
    url: jdbc:mysql://localhost:3306/health
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:templates
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    mvc:
      static-path-pattern: "/static/**"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false


  jpa:
    show-sql: true
    open-in-view: false
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

sever:
  servlet:
    encoding:
      fore-response: true




